# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import modsdb_pb2 as modsdb__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in modsdb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModsDBStub:
    """modsdb API. The same messages are the WAL record payloads.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTable = channel.unary_unary(
                '/modsdb.v1.ModsDB/CreateTable',
                request_serializer=modsdb__pb2.CreateTableRequest.SerializeToString,
                response_deserializer=modsdb__pb2.CommitAck.FromString,
                _registered_method=True)
        self.DropTable = channel.unary_unary(
                '/modsdb.v1.ModsDB/DropTable',
                request_serializer=modsdb__pb2.DropTableRequest.SerializeToString,
                response_deserializer=modsdb__pb2.CommitAck.FromString,
                _registered_method=True)
        self.GetRows = channel.unary_unary(
                '/modsdb.v1.ModsDB/GetRows',
                request_serializer=modsdb__pb2.GetRowsRequest.SerializeToString,
                response_deserializer=modsdb__pb2.Rows.FromString,
                _registered_method=True)
        self.Scan = channel.unary_unary(
                '/modsdb.v1.ModsDB/Scan',
                request_serializer=modsdb__pb2.ScanRequest.SerializeToString,
                response_deserializer=modsdb__pb2.Rows.FromString,
                _registered_method=True)
        self.Apply = channel.unary_unary(
                '/modsdb.v1.ModsDB/Apply',
                request_serializer=modsdb__pb2.WriteBatch.SerializeToString,
                response_deserializer=modsdb__pb2.CommitAck.FromString,
                _registered_method=True)
        self.FetchAndMark = channel.unary_unary(
                '/modsdb.v1.ModsDB/FetchAndMark',
                request_serializer=modsdb__pb2.FetchAndMarkRequest.SerializeToString,
                response_deserializer=modsdb__pb2.Rows.FromString,
                _registered_method=True)
        self.Stats = channel.unary_unary(
                '/modsdb.v1.ModsDB/Stats',
                request_serializer=modsdb__pb2.Empty.SerializeToString,
                response_deserializer=modsdb__pb2.StatsResponse.FromString,
                _registered_method=True)


class ModsDBServicer:
    """modsdb API. The same messages are the WAL record payloads.
    """

    def CreateTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DropTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Scan(self, request, context):
        """whole table, optional status filter
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Apply(self, request, context):
        """atomic multi-op write
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchAndMark(self, request, context):
        """atomic read + patch (worker fetch)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModsDBServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTable': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTable,
                    request_deserializer=modsdb__pb2.CreateTableRequest.FromString,
                    response_serializer=modsdb__pb2.CommitAck.SerializeToString,
            ),
            'DropTable': grpc.unary_unary_rpc_method_handler(
                    servicer.DropTable,
                    request_deserializer=modsdb__pb2.DropTableRequest.FromString,
                    response_serializer=modsdb__pb2.CommitAck.SerializeToString,
            ),
            'GetRows': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRows,
                    request_deserializer=modsdb__pb2.GetRowsRequest.FromString,
                    response_serializer=modsdb__pb2.Rows.SerializeToString,
            ),
            'Scan': grpc.unary_unary_rpc_method_handler(
                    servicer.Scan,
                    request_deserializer=modsdb__pb2.ScanRequest.FromString,
                    response_serializer=modsdb__pb2.Rows.SerializeToString,
            ),
            'Apply': grpc.unary_unary_rpc_method_handler(
                    servicer.Apply,
                    request_deserializer=modsdb__pb2.WriteBatch.FromString,
                    response_serializer=modsdb__pb2.CommitAck.SerializeToString,
            ),
            'FetchAndMark': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchAndMark,
                    request_deserializer=modsdb__pb2.FetchAndMarkRequest.FromString,
                    response_serializer=modsdb__pb2.Rows.SerializeToString,
            ),
            'Stats': grpc.unary_unary_rpc_method_handler(
                    servicer.Stats,
                    request_deserializer=modsdb__pb2.Empty.FromString,
                    response_serializer=modsdb__pb2.StatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'modsdb.v1.ModsDB', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('modsdb.v1.ModsDB', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModsDB:
    """modsdb API. The same messages are the WAL record payloads.
    """

    @staticmethod
    def CreateTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modsdb.v1.ModsDB/CreateTable',
            modsdb__pb2.CreateTableRequest.SerializeToString,
            modsdb__pb2.CommitAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DropTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modsdb.v1.ModsDB/DropTable',
            modsdb__pb2.DropTableRequest.SerializeToString,
            modsdb__pb2.CommitAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modsdb.v1.ModsDB/GetRows',
            modsdb__pb2.GetRowsRequest.SerializeToString,
            modsdb__pb2.Rows.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Scan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modsdb.v1.ModsDB/Scan',
            modsdb__pb2.ScanRequest.SerializeToString,
            modsdb__pb2.Rows.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Apply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modsdb.v1.ModsDB/Apply',
            modsdb__pb2.WriteBatch.SerializeToString,
            modsdb__pb2.CommitAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchAndMark(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modsdb.v1.ModsDB/FetchAndMark',
            modsdb__pb2.FetchAndMarkRequest.SerializeToString,
            modsdb__pb2.Rows.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modsdb.v1.ModsDB/Stats',
            modsdb__pb2.Empty.SerializeToString,
            modsdb__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
